services:
  mongo:
    image: mongo:7
    container_name: rpg_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: rpgdb
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:1
    depends_on: [mongo]
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin

volumes:
  mongo_data:
